# in docker-compose.yml

services:
  app:
    build: . # Usa il Dockerfile principale
    container_name: research_app
    ports:
      - "8000:8000" # Espone la porta di FastAPI
    env_file:
      - .env
    depends_on:
      - postgres_db
      - qdrant
      - ollama
    volumes:
      - ./src:/app/src
      - ./data:/app/data # Necessario per il salvataggio temporaneo del CSV
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  streamlit_ui:
    build: . # Usa lo stesso Dockerfile principale
    container_name: streamlit_ui
    ports:
      - "8501:8501" # Espone la porta di Streamlit
    env_file:
      - .env
    depends_on:
      - app # Streamlit dipende dal backend
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./streamlit_app.py:/app/streamlit_app.py
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped

  ollama:
    build: ./ollama_setup
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data_host:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data_host:/qdrant/storage
    restart: unless-stopped

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data_host:/var/lib/postgresql/data
    restart: unless-stopped